name: Version Check

on:
  pull_request:
    branches:
      - 'master'
    types: [opened, synchronize]

permissions:
  pull-requests: write
  
jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Fetch origin master
      run: git fetch origin master
    - name: Check version increment
      run: |
        CURRENT_VERSION=$(jq -r '.version' package.json)
        if git show origin/master:package.json > /dev/null 2>&1; then
          BASE_VERSION=$(git show origin/master:package.json | jq -r '.version')
          if [ "$CURRENT_VERSION" == "$BASE_VERSION" ]; then
            echo "Version number has not been incremented."
            exit 1
          fi
        else
          echo "origin/master branch does not exist."
          exit 1
        fi
    - name: Update PR
      if: failure()
      run: |
        gh pr comment ${{ github.event.pull_request.number }} --body "Please increment the version number in package.json."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
