name: Version Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Check version increment
      run: |
        CURRENT_VERSION=$(jq -r '.version' package.json)
        BASE_VERSION=$(git show origin/main:package.json | jq -r '.version')
        if [ "$CURRENT_VERSION" == "$BASE_VERSION" ]; then
          echo "Version number has not been incremented."
          exit 1
        fi